# constants.py
# sound effects from https://pixabay.com/sound-effects/search/wav/

SCREEN_WIDTH = 1360
SCREEN_HEIGHT = 670 # originally 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED_STEP = 0.20
SHOT_RADIUS = 5
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.1